Contactos3.Backend/Models/BrouchureView.cs
namespace Contactos3.Backend.Models
{
    using Contactos3.Domain.Models;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    [NotMapped]
    public class BrouchureView : Brouchure
    {
        [Display(Name = "Image Perfil")]
        public HttpPostedFileBase ImageBrouchureFile { get; set; }
    }
}

Contactos3.Backend/Controllers/BrouchuresController.cs
namespace Contactos3.Backend.Controllers
{
    using System.Data.Entity;
    using System.Threading.Tasks;
    using System.Net;
    using System.Web.Mvc;
    using Contactos3.Backend.Models;
    using Contactos3.Domain.Models;
    using Contactos3.Backend.Helpers;
    using System;

    [Authorize]
    public class BrouchuresController : Controller
    {
        private DataContextLocal db = new DataContextLocal();

        // GET: Brouchures
        public async Task<ActionResult> Index()
        {
            var brouchures = db.Brouchures.Include(b => b.Perfil);
            return View(await brouchures.ToListAsync());
        }

        // GET: Brouchures/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brouchure brouchure = await db.Brouchures.FindAsync(id);
            if (brouchure == null)
            {
                return HttpNotFound();
            }
            return View(brouchure);
        }

        // GET: Brouchures/Create
        public ActionResult Create()
        {
            ViewBag.PerfilId = new SelectList(db.Perfils, "PerfilId", "Name");
            return View();
        }

        // POST: Brouchures/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<ActionResult> Create([Bind(Include = "BrouchureId,PerfilId,BrochureDescription,LastUpdate")] Brouchure brouchure)
        public async Task<ActionResult> Create(BrouchureView view)
        {
            if (ModelState.IsValid)
            {
                var pic = string.Empty;
                var folder = "~/Content/BrouchureImage";

                if (view.ImageBrouchureFile != null)
                {
                    pic = FilesHelper.UploadPhoto(view.ImageBrouchureFile, folder);
                    pic = string.Format("{0}/{1}", folder, pic);
                }

                var brouchure = ToBrouchure(view);
                brouchure.BrouchureImage = pic;
                db.Brouchures.Add(brouchure);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.PerfilId = new SelectList(db.Perfils, "PerfilId", "Name", view.PerfilId);
            return View(view);
        }

        private Brouchure ToBrouchure(BrouchureView view)
        {
            return new Brouchure
            {
                BrochureDescription = view.BrochureDescription,
                BrouchureId = view.BrouchureId,
                BrouchureImage = view.BrouchureImage,
                LastUpdate = view.LastUpdate,
                PerfilId = view.PerfilId,
                Perfil = view.Perfil,

            };
        }

        // GET: Brouchures/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var  brouchure = await db.Brouchures.FindAsync(id);
            if (brouchure == null)
            {
                return HttpNotFound();
            }
            ViewBag.PerfilId = new SelectList(db.Perfils, "PerfilId", "Name", brouchure.PerfilId);

            var view = ToView(brouchure);
            return View(view);
        }

        private BrouchureView ToView(Brouchure brouchure)
        {
            return new BrouchureView
            {
                BrochureDescription = brouchure.BrochureDescription,
                BrouchureId = brouchure.BrouchureId,
                BrouchureImage = brouchure.BrouchureImage,
                LastUpdate = brouchure.LastUpdate,
                PerfilId = brouchure.PerfilId,
                Perfil = brouchure.Perfil,

            };
        }

        // POST: Brouchures/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(BrouchureView view)
        {
            if (ModelState.IsValid)
            {
                var pic = view.BrouchureImage;
                var folder = "~/Content/BrouchureImage";

                if (view.ImageBrouchureFile != null)
                {
                    pic = FilesHelper.UploadPhoto(view.ImageBrouchureFile, folder);
                    pic = string.Format("{0}/{1}", folder, pic);
                }

                var brouchure = ToBrouchure(view);
                brouchure.BrouchureImage = pic;
                db.Entry(brouchure).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.PerfilId = new SelectList(db.Perfils, "PerfilId", "Name", view.PerfilId);
            return View(view);
        }

        // GET: Brouchures/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brouchure brouchure = await db.Brouchures.FindAsync(id);
            if (brouchure == null)
            {
                return HttpNotFound();
            }
            return View(brouchure);
        }

        // POST: Brouchures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Brouchure brouchure = await db.Brouchures.FindAsync(id);
            db.Brouchures.Remove(brouchure);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Contactos3.Backend/Views/Brouchures/Create.cshtml
@model Contactos3.Backend.Models.BrouchureView

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Brouchures", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Brouchure</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PerfilId, "PerfilId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PerfilId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PerfilId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageBrouchureFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.ImageBrouchureFile, new { type = "file" })
                </span>
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.BrochureDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrochureDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrochureDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastUpdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastUpdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastUpdate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Contactos3.Backend/Views/Brouchures/Delete.cshtml
@model Contactos3.Domain.Models.Brouchure

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Brouchure</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Perfil.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Perfil.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrochureDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrochureDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastUpdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastUpdate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Contactos3.Backend/Views/Brouchures/Details.cshtml
@model Contactos3.Domain.Models.Brouchure

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Brouchure</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Perfil.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Perfil.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrochureDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrochureDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastUpdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastUpdate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BrouchureId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Contactos3.Backend/Views/Brouchures/Edit.cshtml
@model Contactos3.Backend.Models.BrouchureView

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Brouchures", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Brouchure</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BrouchureId)
        @Html.HiddenFor(model => model.BrouchureImage)

        <div class="form-group">
            @Html.LabelFor(model => model.PerfilId, "PerfilId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PerfilId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PerfilId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageBrouchureFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.ImageBrouchureFile, new { type = "file" })
                </span>
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.BrochureDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrochureDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrochureDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastUpdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastUpdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastUpdate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Contactos3.Backend/Views/Brouchures/Index.cshtml
@model IEnumerable<Contactos3.Domain.Models.Brouchure>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Perfil.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BrouchureImage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BrochureDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastUpdate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Perfil.Name)
        </td>
        <td>
            @if (!string.IsNullOrEmpty(item.BrouchureImage))
            {
                <img src="@Url.Content(item.BrouchureImage)" alt="Image" style="width:100px;height:150px;max-width: 100%; height: auto;" />
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BrochureDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastUpdate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.BrouchureId }) |
            @Html.ActionLink("Details", "Details", new { id=item.BrouchureId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.BrouchureId })
        </td>
    </tr>
}

</table>