Contactos3.Backend/Models/PerfilView.cs
namespace Contactos3.Backend.Models
{
    using Domain.Models;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    [NotMapped]
    public class PerfilView : Perfil
    {
        [Display(Name = "Image Perfil")]
        public HttpPostedFileBase ImagePerfilFile { get; set; }
    }
}

Contactos3.Backend/Controllers/PerfilsController.cs
namespace Contactos3.Backend.Controllers
{
    using System.Data.Entity;
    using System.Threading.Tasks;
    using System.Net;
    using System.Web.Mvc;
    using Contactos3.Backend.Models;
    using Contactos3.Domain.Models;
    using Contactos3.Backend.Helpers;
    using System;

    [Authorize]
    public class PerfilsController : Controller
    {
        private DataContextLocal db = new DataContextLocal();

        // GET: Perfils
        public async Task<ActionResult> Index()
        {
            return View(await db.Perfils.ToListAsync());
        }

        // GET: Perfils/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Perfil perfil = await db.Perfils.FindAsync(id);
            if (perfil == null)
            {
                return HttpNotFound();
            }
            return View(perfil);
        }

        // GET: Perfils/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Perfils/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<ActionResult> Create(PerfilView view)
        //public async Task<ActionResult> Create([Bind(Include = "PerfilId,Name,LastName")] Perfil perfil)
        {
            if (ModelState.IsValid)
            {
                var pic = string.Empty;
                var folder = "~/Content/ImagePerfil";

                if (view.ImagePerfilFile!= null)
                {
                    pic = FilesHelper.UploadPhoto(view.ImagePerfilFile, folder);
                    pic = string.Format("{0}/{1}", folder, pic);
                }

                var perfil = ToPerfil(view);
                perfil.ImagePerfil = pic;
                db.Perfils.Add(perfil);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(view);
        }

        private Perfil ToPerfil(PerfilView view)
        {
            return new Perfil
            {
                Name = view.Name,
                LastName = view.LastName,
                ImagePerfil  = view.ImagePerfil,
                PerfilId = view.PerfilId,
                Addresses = view.Addresses,
                Brouchures = view.Brouchures,
                Emails = view.Emails,
                Jobs = view.Jobs,
                Phones = view.Phones,
                Socials = view.Socials,
                Urls = view.Urls,
                
            }; 
        }

        // GET: Perfils/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var  perfil = await db.Perfils.FindAsync(id);
            if (perfil == null)
            {
                return HttpNotFound();
            }
            var view = ToView(perfil);
            return View(view);
        }

        private PerfilView  ToView(Perfil perfil)
        {
            return new PerfilView
            {
                Name = perfil.Name,
                LastName = perfil.LastName,
                ImagePerfil = perfil.ImagePerfil,
                PerfilId = perfil.PerfilId,
                Addresses = perfil.Addresses,
                Brouchures = perfil.Brouchures,
                Emails = perfil.Emails,
                Jobs = perfil.Jobs,
                Phones = perfil.Phones,
                Socials = perfil.Socials,
                Urls = perfil.Urls,

            };
        }

        // POST: Perfils/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(PerfilView view)
        {
            if (ModelState.IsValid)
            {
                var pic = string.Empty;
                var folder = "~/Content/ImagePerfil";

                if (view.ImagePerfilFile != null)
                {
                    pic = FilesHelper.UploadPhoto(view.ImagePerfilFile, folder);
                    pic = string.Format("{0}/{1}", folder, pic);
                }

                var perfil = ToPerfil(view);
                perfil.ImagePerfil = pic;


                db.Entry(perfil).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(view);
        }

        // GET: Perfils/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Perfil perfil = await db.Perfils.FindAsync(id);
            if (perfil == null)
            {
                return HttpNotFound();
            }
            return View(perfil);
        }

        // POST: Perfils/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Perfil perfil = await db.Perfils.FindAsync(id);
            db.Perfils.Remove(perfil);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Contactos3.Backend/Views/Perfils/Create.cshtml
@model Contactos3.Backend.Models.PerfilView

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Perfils", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Perfil</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePerfilFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.ImagePerfilFile, new { type = "file" })
                </span>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Contactos3.Backend/Views/Perfils/Delete.cshtml
@model Contactos3.Domain.Models.Perfil

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Perfil</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Contactos3.Backend/Views/Perfils/Details.cshtml
@model Contactos3.Domain.Models.Perfil

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Perfil</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PerfilId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Contactos3.Backend/Views/Perfils/Edit.cshtml
@model Contactos3.Backend.Models.PerfilView

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Perfils", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Perfil</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PerfilId)
        @Html.HiddenFor(model => model.ImagePerfil)



        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePerfilFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.ImagePerfilFile, new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Contactos3.Backend/Views/Perfils/Index.cshtml
@model IEnumerable<Contactos3.Domain.Models.Perfil>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ImagePerfil)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @if (!string.IsNullOrEmpty(item.ImagePerfil))
            {
                <img src="@Url.Content(item.ImagePerfil)" alt="Image" style="width:100px;height:150px;max-width: 100%; height: auto;" />
            }
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PerfilId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PerfilId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PerfilId })
        </td>
    </tr>
}

</table>